// <auto-generated />
namespace MCSF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Calc1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Calc1));
        
        string IMigrationMetadata.Id
        {
            get { return "201502080451393_Calc-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
